---
title: "MA Modelling"
output: html_notebook
---


# Creative Logistic Regression Models and Diagnostics

```{r creative regression pt1}

creative.1 <- glm(Creative ~ Type, family = binomial, data = cannabis)

creative.2 <- glm(Creative ~ Type + THC + TotalCBD, family = binomial, data = cannabis)

creative.3 <- glm(Creative ~ THC + TotalCBD, family = binomial, data = cannabis)

creative.4 <- glm(Creative ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC, family = binomial, data = cannabis)

creative.5 <- glm(Creative ~ Type + THC + TotalCBD + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + α.Pinene + β.Pinene + Nerolidol.1 + Nerolidol.2 + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

creative.6 <- glm(Creative ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + Nerolidol.1 + Nerolidol.2 + α.Pinene + β.Pinene + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

library(stargazer)

stargazer(creative.1, creative.2, creative.3, creative.4, creative.5, creative.6, type = "latex", title = "Results of Logistic Regression Models of the `Creative' Variable", intercept.bottom = F,intercept.top = T,digits=2, model.names = T, single.row = T, font.size = "scriptsize")

```

# Focused Models

```{r focused regression pt1}

focused.1 <- glm(Focused ~ Type, family = binomial, data = cannabis)

focused.2 <- glm(Focused ~ Type + THC + TotalCBD, family = binomial, data = cannabis)

focused.3 <- glm(Focused ~ THC + TotalCBD, family = binomial, data = cannabis)

focused.4 <- glm(Focused ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC, family = binomial, data = cannabis)

focused.5 <- glm(Focused ~ Type + THC + TotalCBD + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + α.Pinene + β.Pinene + Nerolidol.1 + Nerolidol.2 + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

focused.6 <- glm(Focused ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + Nerolidol.1 + Nerolidol.2 + α.Pinene + β.Pinene + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

library(stargazer)

stargazer(focused.1, focused.2, focused.3, focused.4, focused.5, focused.6, type = "latex", title = "Results of Logistic Regression Models of the `Focused' Variable", intercept.bottom = F,intercept.top = T,digits=2, model.names = T, single.row = T, font.size = "scriptsize")


```


# Energetic Models

```{r Energetic Models pt1}

energetic.1 <- glm(Energetic ~ Type, family = binomial, data = cannabis)

energetic.2 <- glm(Energetic ~ Type + THC + TotalCBD, family = binomial, data = cannabis)

energetic.3 <- glm(Energetic ~ THC + TotalCBD, family = binomial, data = cannabis)

energetic.4 <- glm(Energetic ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC, family = binomial, data = cannabis)

energetic.5 <- glm(Energetic ~ Type + THC + TotalCBD + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + α.Pinene + β.Pinene + Nerolidol.1 + Nerolidol.2 + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

energetic.6 <- glm(Energetic ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + Nerolidol.1 + Nerolidol.2 + α.Pinene + β.Pinene + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

library(stargazer)

stargazer(energetic.1, energetic.2, energetic.3, energetic.4, energetic.5, energetic.6, type = "latex", title = "Results of Logistic Regression Models of the `Energetic' Variable", intercept.bottom = F,intercept.top = T,digits=2, model.names = T, single.row = T, font.size = "scriptsize")

```


#Sleepy 

```{r Sleep regression pt1}

sleep.1 <- glm(Sleep ~ Type, family = binomial, data = cannabis)

sleep.2 <- glm(Sleep ~ Type + THC + TotalCBD, family = binomial, data = cannabis)

sleep.3 <- glm(Sleep ~ THC + TotalCBD, family = binomial, data = cannabis)

sleep.4 <- glm(Sleep ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC, family = binomial, data = cannabis)

sleep.5 <- glm(Sleep ~ Type + THC + TotalCBD + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + α.Pinene + β.Pinene + Nerolidol.1 + Nerolidol.2 + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

sleep.6 <- glm(Sleep ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + Nerolidol.1 + Nerolidol.2 + α.Pinene + β.Pinene + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

library(stargazer)

stargazer(sleep.1, sleep.2, sleep.3, sleep.4, sleep.5, sleep.6, type = "latex", title = "Results of Logistic Regression Models of the `Sleep' Variable", intercept.bottom = F,intercept.top = T,digits=2, model.names = T, single.row = T, font.size = "scriptsize")

```


#Combined Models

```{r Mood models pt1}
mood.1 <- glm(Mood ~ Type, family = binomial, data = cannabis)

mood.2 <- glm(Mood ~ Type + THC + TotalCBD, family = binomial, data = cannabis)

mood.3 <- glm(Mood ~ THC + TotalCBD, family = binomial, data = cannabis)

mood.4 <- glm(Mood ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC, family = binomial, data = cannabis)

mood.5 <- glm(Mood ~ Type + THC + TotalCBD + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + α.Pinene + β.Pinene + Nerolidol.1 + Nerolidol.2 + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

mood.6 <- glm(Mood ~ Type + THC + TotalCBD + THCA + Δ9.THC + CBDA + CBDVA + CBG + CBC + Terpinolene + Myrcene + Linalool + Guaiol + D.Limonene + Nerolidol.1 + Nerolidol.2 + α.Pinene + β.Pinene + β.Caryophyllene + α.Humelene + α.Bisabolol, family = binomial, data = cannabis)

library(stargazer)

stargazer(mood.1, mood.2, mood.3, mood.4, mood.5, mood.6, type = "latex", title = "Results of Logistic Regression Models of the `Mood Improvement' Variable", intercept.bottom = F,intercept.top = T,digits=2, model.names = T, single.row = T, font.size = "scriptsize")

```

cannabis[28,]

